version: '2'
services:
# Nginx proxy pass frontends
    search_frontend:
        container_name: search_frontend
        image: nginx
        links:
            - searchsite
        volumes_from:
            - searchsite
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d:ro
            - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
            - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
        ports:
            - 80:80

# Search testing
    searchsite:
        container_name: searchsite
        build:
            context: ./docker/searchsite
        volumes:
            - ./docker/searchsite/php.ini:/usr/local/etc/php/php.ini:ro
            - ./application:/var/www/html
        links:
            - search_metadataserver:metadata
            - search_policyserver:policy
            - search_sitedb:sitedb
            - search_elasticdb:elasticdb
        environment:
            CORS_ENABLED: 1
            TIMEZONE: America/Los_Angeles
            METADATA_PORT: tcp://metadata:8121
            POLICY_PORT: tcp://policy:8181
            SITEDB_ADDR: sitedb
            SITEDB_PORT: 5432
            SITEDB_USER: search
            SITEDB_PASSWORD: search
            SITEDB_DB_NAME: search
            SITEDB_DBDRIVER: postgre
            XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
            GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
            PHP_IDE_CONFIG: serverName=PacificaSearch
        ports:
            - 9000:9000

    search_sitedb:
        container_name: search_sitedb
        image: postgres
        environment:
            POSTGRES_PASSWORD: search
            POSTGRES_DB: search
            POSTGRES_USER: search
        ports:
            - 45432:5432

# Metadata and policy servers
    search_elasticdb:
     container_name: search_elasticdb

     build:
        context: ./docker/tunnel
     volumes:
       - $HOME/.ssh/tunnel-config:/root/.ssh:ro
     ports:
       - 9200:9200
     environment:
       ELASTICDB_PORT: tcp://elasticdb:9200
       TUNNEL_HOST: pacifica-tunnel
       REMOTE_HOST: esmaster-dev.my.emsl.pnl.gov
       LOCAL_PORT: 9200
       REMOTE_PORT: 9200


#  SSH TUNNEL DOCKER CONFIGS

    search_metadataserver:
      container_name: search_metadataserver
      # image: cagataygurturk/docker-ssh-tunnel
      build:
        context: ./docker/tunnel
      volumes:
        - $HOME/.ssh/tunnel-config:/root/ssh:ro
      environment:
        ELASTICDB_PORT: tcp://elasticdb:9200
        TUNNEL_HOST: pacifica-tunnel
        REMOTE_HOST: myemsl-dev-mgmt.emsl.pnl.gov
        LOCAL_PORT: 8121
        REMOTE_PORT: 8121

    search_policyserver:
      container_name: search_policyserver
      # image: cagataygurturk/docker-ssh-tunnel
      build:
        context: ./docker/tunnel
      volumes:
        - $HOME/.ssh/tunnel-config:/root/ssh:ro
      environment:
        ELASTICDB_PORT: tcp://elasticdb:9200
        TUNNEL_HOST: pacifica-tunnel
        REMOTE_HOST: myemsl-dev-mgmt.emsl.pnl.gov
        LOCAL_PORT: 8181
        REMOTE_PORT: 8181

# END SSH TUNNEL DOCKER CONFIGS
