pacifica_search_homepage:
    path:     /
    # Note: Since we use the Symfony convention of naming our services after their fully-namespaced classes, this is a
    # reference to the SearchController *service*, not directly a reference to the class.
    defaults: { _controller: "PacificaSearchBundle\\Controller\\SearchController:indexAction" }

rest:
    type: rest
    resource: PacificaSearchBundle\Controller\RestController